id: PFBC4D5C5
initial_creation_type: input
source_metadata:
  title: Sakya Trichen
  language: fr
  description: 'Texts by and about Kyabgön Sakya Gongma Rinpoche, Ngawang Kunga Tekchen
    Palbar (ngag dbang kun dga'' theg chen dpal ''bar, b. 1945), the 41st Sakya Trizin:'
  volume:
    50cfd01500d541199efcd0cd58492234:
      title: A Prayer for the Long Life of Ngawang Kunga Tekchen Palbar Trinlé Wangi
        Gyalpo, the Lord of Refuge and Precious Holder of the Throne of the Drolma
        Palace at Glorious Sakya
      parent: Long Life Prayers
    8a51621f79d74db79f3a1fb891ff8d97:
      title: Gentle Rain of the Nectar of Immortality
      parent: Long Life Prayers
    fc57f7c8fb644fb4a7118ac1f3f04461:
      title: Prayer for the Long Life of His Holiness the Fourteenth Dalai Lama
      parent: Long Life Prayers
    c7c43bf54a2c4a52b463ea042f9cb32d:
      title: Prayer for the Long Life of Kyabgön Sakya Trichen
      parent: Long Life Prayers
    748fc92fdf394472b8bcdda2086f3c9f:
      title: 'Cymbals to Invoke a Compassionate Response: A Prayer for Swift Rebirth
        of Khandro Tsering Chödrön'
      parent: Swift Rebirth Prayers
created_at: '2022-03-01T01:27:56.821696'
last_modified_at: '2022-03-01T01:27:56.821698'
